! Warning! This file is generated from the file 'Utilities/gencity.inf'.
! DO NOT EDIT THIS FILE BY HAND.

City_Class City_20_21 "20th Ave and 21st St"
with
number 20,
n_to City_18_20_21,
s_to City_20_22_21,
w_to City_20_19_21,
e_to City_20_21_23,
;

City_Class City_20_19_21 "20th Ave between 19th St and 21st St"
with
number 19,
w_to City_20_19,
e_to City_20_21,
d_to Subway_Orange_20_19_21,
;

City_Class City_18_20_21 "21st St between 18th Ave and 20th Ave"
with
number 1,
s_to City_20_21,
;

City_Class City_20_23 "20th Ave and 23rd St"
with
number 22,
n_to City_18_20_23,
s_to City_20_22_23,
w_to City_20_21_23,
e_to City_20_23_25,
;

City_Class City_20_21_23 "20th Ave between 21st St and 23rd St"
with
number 21,
w_to City_20_21,
e_to City_20_23,
;

City_Class City_18_20_23 "23rd St between 18th Ave and 20th Ave"
with
number 3,
s_to City_20_23,
;

City_Class City_20_25 "20th Ave and 25th St"
with
number 24,
n_to City_18_20_25,
s_to City_20_22_25,
w_to City_20_23_25,
e_to City_20_25_27,
;

City_Class City_20_23_25 "20th Ave between 23rd St and 25th St"
with
number 23,
w_to City_20_23,
e_to City_20_25,
d_to Storm_20_23_25,
;

Storm_Class Storm_20_23_25 "Storm Drain below 20th Ave between 23rd St and 25th St"
with
number 523,
u_to City_20_23_25,
s_to Storm_22_23_25,
w_to Storm_Junction_20_23,
;

City_Class City_18_20_25 "25th St between 18th Ave and 20th Ave"
with
number 5,
s_to City_20_25,
;

City_Class City_20_27 "20th Ave and 27th St"
with
number 26,
n_to City_18_20_27,
s_to City_20_22_27,
w_to City_20_25_27,
e_to City_20_27_29,
;

City_Class City_20_25_27 "20th Ave between 25th St and 27th St"
with
number 25,
w_to City_20_25,
e_to City_20_27,
;

City_Class City_18_20_27 "27th St between 18th Ave and 20th Ave"
with
number 7,
s_to City_20_27,
;

City_Class City_20_29 "20th Ave and 29th St"
with
number 28,
n_to City_18_20_29,
s_to City_20_22_29,
w_to City_20_27_29,
e_to City_20_29_31,
;

City_Class City_20_27_29 "20th Ave between 27th St and 29th St"
with
number 27,
w_to City_20_27,
e_to City_20_29,
;

City_Class City_18_20_29 "29th St between 18th Ave and 20th Ave"
with
number 9,
s_to City_20_29,
;

City_Class City_20_31 "20th Ave and 31st St"
with
number 30,
n_to City_18_20_31,
s_to City_20_22_31,
w_to City_20_29_31,
e_to City_20_31_33,
;

City_Class City_20_29_31 "20th Ave between 29th St and 31st St"
with
number 29,
w_to City_20_29,
e_to City_20_31,
d_to Storm_20_29_31,
;

Storm_Class Storm_20_29_31 "Storm Drain below 20th Ave between 29th St and 31st St"
with
number 529,
u_to City_20_29_31,
s_to Storm_22_29_31,
w_to Storm_Junction_20_29,
;

City_Class City_18_20_31 "31st St between 18th Ave and 20th Ave"
with
number 11,
s_to City_20_31,
;

City_Class City_20_33 "20th Ave and 33rd St"
with
number 32,
n_to City_18_20_33,
s_to City_20_22_33,

w_to City_20_31_33,
e_to City_20_33_35,
;

City_Class City_20_31_33 "20th Ave between 31st St and 33rd St"
with
number 31,
w_to City_20_31,
e_to City_20_33,
;

City_Class City_18_20_33 "33rd St between 18th Ave and 20th Ave"
with
number 13,
s_to City_20_33,
;

City_Class City_20_35 "20th Ave and 35th St"
with
number 34,
n_to City_18_20_35,
s_to City_20_22_35,
w_to City_20_33_35,
e_to City_20_35_37,
d_to Subway_Blue_20_35,
;

City_Class City_20_33_35 "20th Ave between 33rd St and 35th St"
with
number 33,
w_to City_20_33,
e_to City_20_35,
;

City_Class City_18_20_35 "35th St between 18th Ave and 20th Ave"
with
number 15,
s_to City_20_35,
d_to Subway_Blue_18_20_35,
;

City_Class City_20_37 "20th Ave and 37th St"
with
number 36,
n_to City_18_20_37,
s_to City_20_22_37,
w_to City_20_35_37,
e_to City_20_37_39,
;

City_Class City_20_35_37 "20th Ave between 35th St and 37th St"
with
number 35,
w_to City_20_35,
e_to City_20_37,
;

City_Class City_18_20_37 "37th St between 18th Ave and 20th Ave"
with
number 17,
s_to City_20_37,
;

City_Class City_20_37_39 "20th Ave between 37th St and 39th St"
with
number 37,
w_to City_20_37,
d_to Storm_20_37_39,
;

Storm_Class Storm_20_37_39 "Storm Drain below 20th Ave between 37th St and 39th St"
with
number 537,
u_to City_20_37_39,
s_to Storm_22_37_39,
w_to Storm_Junction_20_37,
;

City_Class City_22_21 "22nd Ave and 21st St"
with
number 58,
n_to City_20_22_21,
s_to City_22_24_21,
w_to City_22_19_21,
e_to City_22_21_23,
;

City_Class City_22_19_21 "22nd Ave between 19th St and 21st St"
with
number 57,
e_to City_22_21,
d_to Subway_Green_22_19_21,
;

City_Class City_20_22_21 "21st St between 20th Ave and 22nd Ave"
with
number 39,
n_to City_20_21,
s_to City_22_21,
d_to Subway_Orange_20_22_21,
;

Storm_Class Storm_20_22_21 "Storm Drain below 21st St between 20th Ave and 22nd Ave"
with
number 539,
u_to Subway_Orange_20_22_21,
e_to Storm_20_22_23,
n_to Storm_Junction_20_19,
;

City_Class City_22_23 "22nd Ave and 23rd St"
with
number 60,
n_to City_20_22_23,
s_to City_22_24_23,
w_to City_22_21_23,
e_to City_22_23_25,
;

City_Class City_22_21_23 "22nd Ave between 21st St and 23rd St"
with
number 59,
w_to City_22_21,
e_to City_22_23,
d_to Subway_Orange_22_21_23,
;

City_Class City_20_22_23 "23rd St between 20th Ave and 22nd Ave"
with
number 41,
n_to City_20_23,
s_to City_22_23,
d_to Storm_20_22_23,
;

Storm_Class Storm_20_22_23 "Storm Drain below 23rd St between 20th Ave and 22nd Ave"
with
number 541,
u_to City_20_22_23,
w_to Storm_20_22_21,
e_to Storm_20_22_25,
n_to Storm_Junction_20_23,
;

City_Class City_22_25 "22nd Ave and 25th St"
with
number 62,
n_to City_20_22_25,
s_to City_22_24_25,
w_to City_22_23_25,
e_to City_22_25_27,
;

City_Class City_22_23_25 "22nd Ave between 23rd St and 25th St"
with
number 61,
w_to City_22_23,
e_to City_22_25,
d_to Storm_22_23_25,

;

Storm_Class Storm_22_23_25 "Storm Drain below 22nd Ave between 23rd St and 25th St"
with
number 561,
u_to City_22_23_25,
n_to Storm_20_23_25,
s_to Storm_24_23_25,
;

City_Class City_20_22_25 "25th St between 20th Ave and 22nd Ave"
with
number 43,
n_to City_20_25,
s_to City_22_25,
d_to Storm_20_22_25,
;

Storm_Class Storm_20_22_25 "Storm Drain below 25th St between 20th Ave and 22nd Ave"
with
number 543,
u_to City_20_22_25,
w_to Storm_20_22_23,
e_to Storm_20_22_27,
;

City_Class City_22_27 "22nd Ave and 27th St"
with
number 64,
n_to City_20_22_27,
s_to City_22_24_27,
w_to City_22_25_27,
e_to City_22_27_29,
;

City_Class City_22_25_27 "22nd Ave between 25th St and 27th St"
with
number 63,
w_to City_22_25,
e_to City_22_27,
;

City_Class City_20_22_27 "27th St between 20th Ave and 22nd Ave"
with
number 45,
n_to City_20_27,
s_to City_22_27,
d_to Storm_20_22_27,
;

Storm_Class Storm_20_22_27 "Storm Drain below 27th St between 20th Ave and 22nd Ave"
with
number 545,
u_to City_20_22_27,
w_to Storm_20_22_25,
e_to Storm_20_22_29,
;

City_Class City_22_29 "22nd Ave and 29th St"
with
number 66,
n_to City_20_22_29,
s_to City_22_24_29,
w_to City_22_27_29,
e_to City_22_29_31,
;

City_Class City_22_27_29 "22nd Ave between 27th St and 29th St"
with
number 65,
w_to City_22_27,
e_to City_22_29,
;

City_Class City_20_22_29 "29th St between 20th Ave and 22nd Ave"
with
number 47,
n_to City_20_29,
s_to City_22_29,
d_to Storm_20_22_29,
;

Storm_Class Storm_20_22_29 "Storm Drain below 29th St between 20th Ave and 22nd Ave"
with
number 547,
u_to City_20_22_29,
w_to Storm_20_22_27,
e_to Storm_20_22_31,
n_to Storm_Junction_20_29,
;

City_Class City_22_31 "22nd Ave and 31st St"
with
number 68,
n_to City_20_22_31,
s_to City_22_24_31,
w_to City_22_29_31,
e_to City_22_31_33,
;

City_Class City_22_29_31 "22nd Ave between 29th St and 31st St"
with
number 67,
w_to City_22_29,
e_to City_22_31,
d_to Storm_22_29_31,
;

Storm_Class Storm_22_29_31 "Storm Drain below 22nd Ave between 29th St and 31st St"
with
number 567,
u_to City_22_29_31,
n_to Storm_20_29_31,
s_to Storm_24_29_31,
;

City_Class City_20_22_31 "31st St between 20th Ave and 22nd Ave"
with
number 49,
n_to City_20_31,
s_to City_22_31,
d_to Storm_20_22_31,
;

Storm_Class Storm_20_22_31 "Storm Drain below 31st St between 20th Ave and 22nd Ave"
with
number 549,
u_to City_20_22_31,
w_to Storm_20_22_29,
e_to Storm_20_22_33,
;

City_Class City_22_33 "22nd Ave and 33rd St"
with
number 70,
n_to City_20_22_33,
s_to City_22_24_33,
w_to City_22_31_33,
e_to City_22_33_35,
;

City_Class City_22_31_33 "22nd Ave between 31st St and 33rd St"
with
number 69,
w_to City_22_31,
e_to City_22_33,
;

City_Class City_20_22_33 "33rd St between 20th Ave and 22nd Ave"
with
number 51,
n_to City_20_33,
s_to City_22_33,
d_to Storm_20_22_33,
;

Storm_Class Storm_20_22_33 "Storm Drain below 33rd St between 20th Ave and 22nd Ave"
with
number 551,

u_to City_20_22_33,
w_to Storm_20_22_31,
e_to Storm_20_22_35,
;

City_Class City_22_35 "22nd Ave and 35th St"
with
number 72,
n_to City_20_22_35,
s_to City_22_24_35,
w_to City_22_33_35,
e_to City_22_35_37,
d_to Subway_Blue_22_35,
;

City_Class City_22_33_35 "22nd Ave between 33rd St and 35th St"
with
number 71,
w_to City_22_33,
e_to City_22_35,
;

City_Class City_20_22_35 "35th St between 20th Ave and 22nd Ave"
with
number 53,
n_to City_20_35,
s_to City_22_35,
d_to Subway_Blue_20_22_35,
;

Storm_Class Storm_20_22_35 "Storm Drain below 35th St between 20th Ave and 22nd Ave"
with
number 553,
u_to Subway_Blue_20_22_35,
w_to Storm_20_22_33,
e_to Storm_20_22_37,
;

City_Class City_22_37 "22nd Ave and 37th St"
with
number 74,
n_to City_20_22_37,
s_to City_22_24_37,
w_to City_22_35_37,
e_to City_22_37_39,
;

City_Class City_22_35_37 "22nd Ave between 35th St and 37th St"
with
number 73,
w_to City_22_35,
e_to City_22_37,
;

City_Class City_20_22_37 "37th St between 20th Ave and 22nd Ave"
with
number 55,
n_to City_20_37,
s_to City_22_37,
d_to Storm_20_22_37,
;

Storm_Class Storm_20_22_37 "Storm Drain below 37th St between 20th Ave and 22nd Ave"
with
number 555,
u_to City_20_22_37,
w_to Storm_20_22_35,
n_to Storm_Junction_20_37,
;

City_Class City_22_37_39 "22nd Ave between 37th St and 39th St"
with
number 75,
w_to City_22_37,
d_to Storm_22_37_39,
;

Storm_Class Storm_22_37_39 "Storm Drain below 22nd Ave between 37th St and 39th St"
with
number 575,
u_to City_22_37_39,
n_to Storm_20_37_39,
s_to Storm_24_37_39,
;

City_Class City_24_21 "24th Ave and 21st St"
with
number 96,
n_to City_22_24_21,
s_to City_24_26_21,
w_to City_24_19_21,
e_to City_24_21_23,
;

City_Class City_24_19_21 "24th Ave between 19th St and 21st St"
with
number 95,
e_to City_24_21,
d_to Subway_Green_24_19_21,
;

City_Class City_22_24_21 "21st St between 22nd Ave and 24th Ave"
with
number 77,
n_to City_22_21,
s_to City_24_21,
;

City_Class City_24_23 "24th Ave and 23rd St"
with
number 98,
n_to City_22_24_23,
s_to City_24_26_23,
w_to City_24_21_23,
e_to City_24_23_25,
;

City_Class City_24_21_23 "24th Ave between 21st St and 23rd St"
with
number 97,
w_to City_24_21,
e_to City_24_23,
;

City_Class City_22_24_23 "23rd St between 22nd Ave and 24th Ave"
with
number 79,
n_to City_22_23,
s_to City_24_23,
d_to Subway_Orange_22_24_23,
;

City_Class City_24_25 "24th Ave and 25th St"
with
number 100,
n_to City_22_24_25,
s_to City_24_26_25,
w_to City_24_23_25,
e_to City_24_25_27,
;

City_Class City_24_23_25 "24th Ave between 23rd St and 25th St"
with
number 99,
w_to City_24_23,
e_to City_24_25,
d_to Storm_24_23_25,
;

Storm_Class Storm_24_23_25 "Storm Drain below 24th Ave between 23rd St and 25th St"
with
number 599,
u_to City_24_23_25,
n_to Storm_22_23_25,
s_to Storm_26_23_25,
;

City_Class City_22_24_25 "25th St between 22nd Ave and 24th Ave"
with

number 81,
n_to City_22_25,
s_to City_24_25,
d_to Subway_Orange_22_24_25,
;

City_Class City_24_27 "24th Ave and 27th St"
with
number 102,
n_to City_22_24_27,
s_to City_24_26_27,
w_to City_24_25_27,
e_to City_24_27_29,
;

City_Class City_24_25_27 "24th Ave between 25th St and 27th St"
with
number 101,
w_to City_24_25,
e_to City_24_27,
;

City_Class City_22_24_27 "27th St between 22nd Ave and 24th Ave"
with
number 83,
n_to City_22_27,
s_to City_24_27,
d_to Subway_Orange_22_24_27,
;

City_Class City_24_29 "24th Ave and 29th St"
with
number 104,
n_to City_22_24_29,
s_to City_24_26_29,
w_to City_24_27_29,
e_to City_24_29_31,
;

City_Class City_24_27_29 "24th Ave between 27th St and 29th St"
with
number 103,
w_to City_24_27,
e_to City_24_29,
;

City_Class City_22_24_29 "29th St between 22nd Ave and 24th Ave"
with
number 85,
n_to City_22_29,
s_to City_24_29,
d_to Subway_Orange_22_24_29,
;

City_Class City_24_31 "24th Ave and 31st St"
with
number 106,
n_to City_22_24_31,
s_to City_24_26_31,
w_to City_24_29_31,
e_to City_24_31_33,
;

City_Class City_24_29_31 "24th Ave between 29th St and 31st St"
with
number 105,
w_to City_24_29,
e_to City_24_31,
d_to Subway_Orange_24_29_31,
;

Storm_Class Storm_24_29_31 "Storm Drain below 24th Ave between 29th St and 31st St"
with
number 605,
u_to Subway_Orange_24_29_31,
n_to Storm_22_29_31,
s_to Storm_26_29_31,
;

City_Class City_22_24_31 "31st St between 22nd Ave and 24th Ave"
with
number 87,
n_to City_22_31,
s_to City_24_31,
;

City_Class City_24_33 "24th Ave and 33rd St"
with
number 108,
n_to City_22_24_33,
s_to City_24_26_33,
w_to City_24_31_33,
e_to City_24_33_35,
;

City_Class City_24_31_33 "24th Ave between 31st St and 33rd St"
with
number 107,
w_to City_24_31,
e_to City_24_33,
;

City_Class City_22_24_33 "33rd St between 22nd Ave and 24th Ave"
with
number 89,
n_to City_22_33,
s_to City_24_33,
;

City_Class City_24_35 "24th Ave and 35th St"
with
number 110,
n_to City_22_24_35,
s_to City_24_26_35,
w_to City_24_33_35,
e_to City_24_35_37,
;

City_Class City_24_33_35 "24th Ave between 33rd St and 35th St"
with
number 109,
w_to City_24_33,
e_to City_24_35,
;

City_Class City_22_24_35 "35th St between 22nd Ave and 24th Ave"
with
number 91,
n_to City_22_35,
s_to City_24_35,
;

City_Class City_24_37 "24th Ave and 37th St"
with
number 112,
n_to City_22_24_37,
s_to City_24_26_37,
w_to City_24_35_37,
e_to City_24_37_39,
;

City_Class City_24_35_37 "24th Ave between 35th St and 37th St"
with
number 111,
w_to City_24_35,
e_to City_24_37,
d_to Subway_Blue_24_35_37,
;

City_Class City_22_24_37 "37th St between 22nd Ave and 24th Ave"
with
number 93,
n_to City_22_37,
s_to City_24_37,
;

City_Class City_24_37_39 "24th Ave between 37th St and 39th St"
with
number 113,

w_to City_24_37,
d_to Storm_24_37_39,
;

Storm_Class Storm_24_37_39 "Storm Drain below 24th Ave between 37th St and 39th St"
with
number 613,
u_to City_24_37_39,
n_to Storm_22_37_39,
s_to Storm_26_37_39,
;

City_Class City_26_21 "26th Ave and 21st St"
with
number 134,
n_to City_24_26_21,
s_to City_26_28_21,
w_to City_26_19_21,
e_to City_26_21_23,
;

City_Class City_26_19_21 "26th Ave between 19th St and 21st St"
with
number 133,
e_to City_26_21,
;

City_Class City_24_26_21 "21st St between 24th Ave and 26th Ave"
with
number 115,
n_to City_24_21,
s_to City_26_21,
d_to Subway_Green_24_26_21,
;

City_Class City_26_23 "26th Ave and 23rd St"
with
number 136,
n_to City_24_26_23,
s_to City_26_28_23,
w_to City_26_21_23,
e_to City_26_23_25,
;

City_Class City_26_21_23 "26th Ave between 21st St and 23rd St"
with
number 135,
w_to City_26_21,
e_to City_26_23,
d_to Subway_Green_26_21_23,
;

City_Class City_24_26_23 "23rd St between 24th Ave and 26th Ave"
with
number 117,
n_to City_24_23,
s_to City_26_23,
;

City_Class City_26_25 "26th Ave and 25th St"
with
number 138,
n_to City_24_26_25,
s_to City_26_28_25,
w_to City_26_23_25,
e_to City_26_25_27,
;

City_Class City_26_23_25 "26th Ave between 23rd St and 25th St"
with
number 137,
w_to City_26_23,
e_to City_26_25,
d_to Storm_26_23_25,
;

Storm_Class Storm_26_23_25 "Storm Drain below 26th Ave between 23rd St and 25th St"
with
number 637,
u_to City_26_23_25,
n_to Storm_24_23_25,
s_to Storm_28_23_25,
;

City_Class City_24_26_25 "25th St between 24th Ave and 26th Ave"
with
number 119,
n_to City_24_25,
s_to City_26_25,
;

City_Class City_26_27 "26th Ave and 27th St"
with
number 140,
n_to City_24_26_27,
s_to City_26_28_27,
w_to City_26_25_27,
e_to City_26_27_29,
;

City_Class City_26_25_27 "26th Ave between 25th St and 27th St"
with
number 139,
w_to City_26_25,
e_to City_26_27,
;

City_Class City_24_26_27 "27th St between 24th Ave and 26th Ave"
with
number 121,
n_to City_24_27,
s_to City_26_27,
;

City_Class City_26_29 "26th Ave and 29th St"
with
number 142,
n_to City_24_26_29,
s_to City_26_28_29,
w_to City_26_27_29,
e_to City_26_29_31,
;

City_Class City_26_27_29 "26th Ave between 27th St and 29th St"
with
number 141,
w_to City_26_27,
e_to City_26_29,
;

City_Class City_24_26_29 "29th St between 24th Ave and 26th Ave"
with
number 123,
n_to City_24_29,
s_to City_26_29,
;

City_Class City_26_31 "26th Ave and 31st St"
with
number 144,
n_to City_24_26_31,
s_to City_26_28_31,
w_to City_26_29_31,
e_to City_26_31_33,
;

City_Class City_26_29_31 "26th Ave between 29th St and 31st St"
with
number 143,
w_to City_26_29,
e_to City_26_31,
d_to Storm_26_29_31,
;

Storm_Class Storm_26_29_31 "Storm Drain below 26th Ave between 29th St and 31st St"
with
number 643,
u_to City_26_29_31,
n_to Storm_24_29_31,

s_to Storm_28_29_31,
;

City_Class City_24_26_31 "31st St between 24th Ave and 26th Ave"
with
number 125,
n_to City_24_31,
s_to City_26_31,
d_to Subway_Orange_24_26_31,
;

City_Class City_26_33 "26th Ave and 33rd St"
with
number 146,
n_to City_24_26_33,
s_to City_26_28_33,
w_to City_26_31_33,
e_to City_26_33_35,
;

City_Class City_26_31_33 "26th Ave between 31st St and 33rd St"
with
number 145,
w_to City_26_31,
e_to City_26_33,
d_to Subway_Orange_26_31_33,
;

City_Class City_24_26_33 "33rd St between 24th Ave and 26th Ave"
with
number 127,
n_to City_24_33,
s_to City_26_33,
;

City_Class City_26_35 "26th Ave and 35th St"
with
number 148,
n_to City_24_26_35,
s_to City_26_28_35,
w_to City_26_33_35,
e_to City_26_35_37,
;

City_Class City_26_33_35 "26th Ave between 33rd St and 35th St"
with
number 147,
w_to City_26_33,
e_to City_26_35,
;

City_Class City_24_26_35 "35th St between 24th Ave and 26th Ave"
with
number 129,
n_to City_24_35,
s_to City_26_35,
;

City_Class City_26_37 "26th Ave and 37th St"
with
number 150,
n_to City_24_26_37,
s_to City_26_28_37,
w_to City_26_35_37,
e_to City_26_37_39,
;

City_Class City_26_35_37 "26th Ave between 35th St and 37th St"
with
number 149,
w_to City_26_35,
e_to City_26_37,
d_to Subway_Blue_26_35_37,
;

City_Class City_24_26_37 "37th St between 24th Ave and 26th Ave"
with
number 131,
n_to City_24_37,
s_to City_26_37,
;

City_Class City_26_37_39 "26th Ave between 37th St and 39th St"
with
number 151,
w_to City_26_37,
d_to Storm_26_37_39,
;

Storm_Class Storm_26_37_39 "Storm Drain below 26th Ave between 37th St and 39th St"
with
number 651,
u_to City_26_37_39,
n_to Storm_24_37_39,
s_to Storm_28_37_39,
;

City_Class City_28_21 "28th Ave and 21st St"
with
number 172,
n_to City_26_28_21,
s_to City_28_30_21,
w_to City_28_19_21,
e_to City_28_21_23,
;

City_Class City_28_19_21 "28th Ave between 19th St and 21st St"
with
number 171,
e_to City_28_21,
;

City_Class City_26_28_21 "21st St between 26th Ave and 28th Ave"
with
number 153,
n_to City_26_21,
s_to City_28_21,
;

City_Class City_28_23 "28th Ave and 23rd St"
with
number 174,
n_to City_26_28_23,
s_to City_28_30_23,
w_to City_28_21_23,
e_to City_28_23_25,
;

City_Class City_28_21_23 "28th Ave between 21st St and 23rd St"
with
number 173,
w_to City_28_21,
e_to City_28_23,
d_to Subway_Green_28_21_23,
;

City_Class City_26_28_23 "23rd St between 26th Ave and 28th Ave"
with
number 155,
n_to City_26_23,
s_to City_28_23,
;

City_Class City_28_25 "28th Ave and 25th St"
with
number 176,
n_to City_26_28_25,
s_to City_28_30_25,
w_to City_28_23_25,
e_to City_28_25_27,
;

City_Class City_28_23_25 "28th Ave between 23rd St and 25th St"
with
number 175,
w_to City_28_23,
e_to City_28_25,
d_to Storm_28_23_25,
;

Storm_Class Storm_28_23_25 "Storm Drain below 28th Ave between 23rd St and 25th St"
with
number 675,
u_to City_28_23_25,
n_to Storm_26_23_25,
s_to Storm_30_23_25,
;

City_Class City_26_28_25 "25th St between 26th Ave and 28th Ave"
with
number 157,
n_to City_26_25,
s_to City_28_25,
;

City_Class City_28_27 "28th Ave and 27th St"
with
number 178,
n_to City_26_28_27,
s_to City_28_30_27,
w_to City_28_25_27,
e_to City_28_27_29,
;

City_Class City_28_25_27 "28th Ave between 25th St and 27th St"
with
number 177,
w_to City_28_25,
e_to City_28_27,
s_to Start_Alley,
;

City_Class City_26_28_27 "27th St between 26th Ave and 28th Ave"
with
number 159,
n_to City_26_27,
s_to City_28_27,
;

City_Class City_28_29 "28th Ave and 29th St"
with
number 180,
n_to City_26_28_29,
s_to City_28_30_29,
w_to City_28_27_29,
e_to City_28_29_31,
;

City_Class City_28_27_29 "28th Ave between 27th St and 29th St"
with
number 179,
w_to City_28_27,
e_to City_28_29,
;

City_Class City_26_28_29 "29th St between 26th Ave and 28th Ave"
with
number 161,
n_to City_26_29,
s_to City_28_29,
;

City_Class City_28_31 "28th Ave and 31st St"
with
number 182,
n_to City_26_28_31,
s_to City_28_30_31,
w_to City_28_29_31,
e_to City_28_31_33,
;

City_Class City_28_29_31 "28th Ave between 29th St and 31st St"
with
number 181,
w_to City_28_29,
e_to City_28_31,
d_to Storm_28_29_31,
;

Storm_Class Storm_28_29_31 "Storm Drain below 28th Ave between 29th St and 31st St"
with
number 681,
u_to City_28_29_31,
n_to Storm_26_29_31,
s_to Storm_30_29_31,
;

City_Class City_26_28_31 "31st St between 26th Ave and 28th Ave"
with
number 163,
n_to City_26_31,
s_to City_28_31,
;

City_Class City_28_33 "28th Ave and 33rd St"
with
number 184,
n_to City_26_28_33,
s_to City_28_30_33,
w_to City_28_31_33,
e_to City_28_33_35,
d_to Subway_Orange_28_33,
;

City_Class City_28_31_33 "28th Ave between 31st St and 33rd St"
with
number 183,
w_to City_28_31,
e_to City_28_33,
;

City_Class City_26_28_33 "33rd St between 26th Ave and 28th Ave"
with
number 165,
n_to City_26_33,
s_to City_28_33,
d_to Subway_Orange_26_28_33,
;

City_Class City_28_35 "28th Ave and 35th St"
with
number 186,
n_to City_26_28_35,
s_to City_28_30_35,
w_to City_28_33_35,
e_to City_28_35_37,
;

City_Class City_28_33_35 "28th Ave between 33rd St and 35th St"
with
number 185,
w_to City_28_33,
e_to City_28_35,
;

City_Class City_26_28_35 "35th St between 26th Ave and 28th Ave"
with
number 167,
n_to City_26_35,
s_to City_28_35,
;

City_Class City_28_37 "28th Ave and 37th St"
with
number 188,
n_to City_26_28_37,
s_to City_28_30_37,
w_to City_28_35_37,
e_to City_28_37_39,
;

City_Class City_28_35_37 "28th Ave between 35th St and 37th St"
with
number 187,
w_to City_28_35,
e_to City_28_37,
d_to Subway_Blue_28_35_37,
;

City_Class City_26_28_37 "37th St between 26th Ave and 28th Ave"
with
number 169,
n_to City_26_37,
s_to City_28_37,
;

City_Class City_28_37_39 "28th Ave between 37th St and 39th St"
with
number 189,
w_to City_28_37,
d_to Storm_28_37_39,
;

Storm_Class Storm_28_37_39 "Storm Drain below 28th Ave between 37th St and 39th St"
with
number 689,
u_to City_28_37_39,
n_to Storm_26_37_39,
s_to Storm_30_37_39,
;

City_Class City_30_21 "30th Ave and 21st St"
with
number 210,
n_to City_28_30_21,
s_to City_30_32_21,
w_to City_30_19_21,
e_to City_30_21_23,
;

City_Class City_30_19_21 "30th Ave between 19th St and 21st St"
with
number 209,
e_to City_30_21,
;

City_Class City_28_30_21 "21st St between 28th Ave and 30th Ave"
with
number 191,
n_to City_28_21,
s_to City_30_21,
;

City_Class City_30_23 "30th Ave and 23rd St"
with
number 212,
n_to City_28_30_23,
s_to City_30_32_23,
w_to City_30_21_23,
e_to City_30_23_25,
;

City_Class City_30_21_23 "30th Ave between 21st St and 23rd St"
with
number 211,
w_to City_30_21,
e_to City_30_23,
d_to Subway_Green_30_21_23,
;

City_Class City_28_30_23 "23rd St between 28th Ave and 30th Ave"
with
number 193,
n_to City_28_23,
s_to City_30_23,
;

City_Class City_30_25 "30th Ave and 25th St"
with
number 214,
n_to City_28_30_25,
s_to City_30_32_25,
w_to City_30_23_25,
e_to City_30_25_27,
;

City_Class City_30_23_25 "30th Ave between 23rd St and 25th St"
with
number 213,
w_to City_30_23,
e_to City_30_25,
d_to Storm_30_23_25,
;

Storm_Class Storm_30_23_25 "Storm Drain below 30th Ave between 23rd St and 25th St"
with
number 713,
u_to City_30_23_25,
n_to Storm_28_23_25,
s_to Storm_32_23_25,
w_to Storm_Junction_30_23,
;

City_Class City_28_30_25 "25th St between 28th Ave and 30th Ave"
with
number 195,
n_to City_28_25,
s_to City_30_25,
;

City_Class City_30_27 "30th Ave and 27th St"
with
number 216,
n_to City_28_30_27,
s_to City_30_32_27,
w_to City_30_25_27,
e_to City_30_27_29,
;

City_Class City_30_25_27 "30th Ave between 25th St and 27th St"
with
number 215,
w_to City_30_25,
e_to City_30_27,
;

City_Class City_28_30_27 "27th St between 28th Ave and 30th Ave"
with
number 197,
n_to City_28_27,
s_to City_30_27,
;

City_Class City_30_29 "30th Ave and 29th St"
with
number 218,
n_to City_28_30_29,
s_to City_30_32_29,
w_to City_30_27_29,
e_to City_30_29_31,
;

City_Class City_30_27_29 "30th Ave between 27th St and 29th St"
with
number 217,
w_to City_30_27,
e_to City_30_29,
;

City_Class City_28_30_29 "29th St between 28th Ave and 30th Ave"
with
number 199,
n_to City_28_29,
s_to City_30_29,
;

City_Class City_30_31 "30th Ave and 31st St"
with
number 220,
n_to City_28_30_31,
s_to City_30_32_31,
w_to City_30_29_31,
e_to City_30_31_33,
;

City_Class City_30_29_31 "30th Ave between 29th St and 31st St"
with

number 219,
w_to City_30_29,
e_to City_30_31,
d_to Storm_30_29_31,
;

Storm_Class Storm_30_29_31 "Storm Drain below 30th Ave between 29th St and 31st St"
with
number 719,
u_to City_30_29_31,
n_to Storm_28_29_31,
s_to Storm_32_29_31,
w_to Storm_Junction_30_29,
;

City_Class City_28_30_31 "31st St between 28th Ave and 30th Ave"
with
number 201,
n_to City_28_31,
s_to City_30_31,
;

City_Class City_30_33 "30th Ave and 33rd St"
with
number 222,
n_to City_28_30_33,
s_to City_30_32_33,
w_to City_30_31_33,
e_to City_30_33_35,
d_to Subway_Orange_30_33,
;

City_Class City_30_31_33 "30th Ave between 31st St and 33rd St"
with
number 221,
w_to City_30_31,
e_to City_30_33,
;

City_Class City_28_30_33 "33rd St between 28th Ave and 30th Ave"
with
number 203,
n_to City_28_33,
s_to City_30_33,
d_to Subway_Orange_28_30_33,
;

City_Class City_30_35 "30th Ave and 35th St"
with
number 224,
n_to City_28_30_35,
s_to City_30_32_35,
w_to City_30_33_35,
e_to City_30_35_37,
;

City_Class City_30_33_35 "30th Ave between 33rd St and 35th St"
with
number 223,
w_to City_30_33,
e_to City_30_35,
;

City_Class City_28_30_35 "35th St between 28th Ave and 30th Ave"
with
number 205,
n_to City_28_35,
s_to City_30_35,
;

City_Class City_30_37 "30th Ave and 37th St"
with
number 226,
n_to City_28_30_37,
s_to City_30_32_37,
w_to City_30_35_37,
e_to City_30_37_39,
;

City_Class City_30_35_37 "30th Ave between 35th St and 37th St"
with
number 225,
w_to City_30_35,
e_to City_30_37,
;

City_Class City_28_30_37 "37th St between 28th Ave and 30th Ave"
with
number 207,
n_to City_28_37,
s_to City_30_37,
;

City_Class City_30_37_39 "30th Ave between 37th St and 39th St"
with
number 227,
w_to City_30_37,
d_to Storm_30_37_39,
;

Storm_Class Storm_30_37_39 "Storm Drain below 30th Ave between 37th St and 39th St"
with
number 727,
u_to City_30_37_39,
n_to Storm_28_37_39,
s_to Storm_32_37_39,
w_to Storm_Junction_30_37,
;

City_Class City_32_21 "32nd Ave and 21st St"
with
number 248,
n_to City_30_32_21,
s_to City_32_34_21,
w_to City_32_19_21,
e_to City_32_21_23,
;

City_Class City_32_19_21 "32nd Ave between 19th St and 21st St"
with
number 247,
e_to City_32_21,
;

City_Class City_30_32_21 "21st St between 30th Ave and 32nd Ave"
with
number 229,
n_to City_30_21,
s_to City_32_21,
d_to Storm_30_32_21,
;

Storm_Class Storm_30_32_21 "Storm Drain below 21st St between 30th Ave and 32nd Ave"
with
number 729,
u_to City_30_32_21,
e_to Storm_30_32_23,
;

City_Class City_32_34_21 "21st St between 32nd Ave and 34th Ave"
with
number 267,
n_to City_32_21,
;

City_Class City_32_23 "32nd Ave and 23rd St"
with
number 250,
n_to City_30_32_23,
s_to City_32_34_23,
w_to City_32_21_23,
e_to City_32_23_25,
;

City_Class City_32_21_23 "32nd Ave between 21st St and 23rd St"
with
number 249,
w_to City_32_21,
e_to City_32_23,

d_to Subway_Green_32_21_23,
;

City_Class City_30_32_23 "23rd St between 30th Ave and 32nd Ave"
with
number 231,
n_to City_30_23,
s_to City_32_23,
d_to Storm_30_32_23,
;

Storm_Class Storm_30_32_23 "Storm Drain below 23rd St between 30th Ave and 32nd Ave"
with
number 731,
u_to City_30_32_23,
w_to Storm_30_32_21,
e_to Storm_30_32_25,
n_to Storm_Junction_30_23,
;

City_Class City_32_34_23 "23rd St between 32nd Ave and 34th Ave"
with
number 269,
n_to City_32_23,
d_to Subway_Green_32_34_23,
;

City_Class City_32_25 "32nd Ave and 25th St"
with
number 252,
n_to City_30_32_25,
s_to City_32_34_25,
w_to City_32_23_25,
e_to City_32_25_27,
;

City_Class City_32_23_25 "32nd Ave between 23rd St and 25th St"
with
number 251,
w_to City_32_23,
e_to City_32_25,
d_to Storm_32_23_25,
;

Storm_Class Storm_32_23_25 "Storm Drain below 32nd Ave between 23rd St and 25th St"
with
number 751,
u_to City_32_23_25,
n_to Storm_30_23_25,
;

City_Class City_30_32_25 "25th St between 30th Ave and 32nd Ave"
with
number 233,
n_to City_30_25,
s_to City_32_25,
d_to Storm_30_32_25,
;

Storm_Class Storm_30_32_25 "Storm Drain below 25th St between 30th Ave and 32nd Ave"
with
number 733,
u_to City_30_32_25,
w_to Storm_30_32_23,
e_to Storm_30_32_27,
;

City_Class City_32_34_25 "25th St between 32nd Ave and 34th Ave"
with
number 271,
n_to City_32_25,
;

City_Class City_32_27 "32nd Ave and 27th St"
with
number 254,
n_to City_30_32_27,
s_to City_32_34_27,
w_to City_32_25_27,
e_to City_32_27_29,
;

City_Class City_32_25_27 "32nd Ave between 25th St and 27th St"
with
number 253,
w_to City_32_25,
e_to City_32_27,
;

City_Class City_30_32_27 "27th St between 30th Ave and 32nd Ave"
with
number 235,
n_to City_30_27,
s_to City_32_27,
d_to Storm_30_32_27,
;

Storm_Class Storm_30_32_27 "Storm Drain below 27th St between 30th Ave and 32nd Ave"
with
number 735,
u_to City_30_32_27,
w_to Storm_30_32_25,
e_to Storm_30_32_29,
;

City_Class City_32_34_27 "27th St between 32nd Ave and 34th Ave"
with
number 273,
n_to City_32_27,
;

City_Class City_32_29 "32nd Ave and 29th St"
with
number 256,
n_to City_30_32_29,
s_to City_32_34_29,
w_to City_32_27_29,
e_to City_32_29_31,
;

City_Class City_32_27_29 "32nd Ave between 27th St and 29th St"
with
number 255,
w_to City_32_27,
e_to City_32_29,
;

City_Class City_30_32_29 "29th St between 30th Ave and 32nd Ave"
with
number 237,
n_to City_30_29,
s_to City_32_29,
d_to Storm_30_32_29,
;

Storm_Class Storm_30_32_29 "Storm Drain below 29th St between 30th Ave and 32nd Ave"
with
number 737,
u_to City_30_32_29,
w_to Storm_30_32_27,
e_to Storm_30_32_31,
n_to Storm_Junction_30_29,
;

City_Class City_32_34_29 "29th St between 32nd Ave and 34th Ave"
with
number 275,
n_to City_32_29,
;

City_Class City_32_31 "32nd Ave and 31st St"
with
number 258,
n_to City_30_32_31,
s_to City_32_34_31,
w_to City_32_29_31,
e_to City_32_31_33,
;

City_Class City_32_29_31 "32nd Ave between 29th St and 31st St"
with
number 257,
w_to City_32_29,
e_to City_32_31,
d_to Storm_32_29_31,
;

Storm_Class Storm_32_29_31 "Storm Drain below 32nd Ave between 29th St and 31st St"
with
number 757,
u_to City_32_29_31,
n_to Storm_30_29_31,
;

City_Class City_30_32_31 "31st St between 30th Ave and 32nd Ave"
with
number 239,
n_to City_30_31,
s_to City_32_31,
d_to Storm_30_32_31,
;

Storm_Class Storm_30_32_31 "Storm Drain below 31st St between 30th Ave and 32nd Ave"
with
number 739,
u_to City_30_32_31,
w_to Storm_30_32_29,
e_to Storm_30_32_33,
;

City_Class City_32_34_31 "31st St between 32nd Ave and 34th Ave"
with
number 277,
n_to City_32_31,
;

City_Class City_32_33 "32nd Ave and 33rd St"
with
number 260,
n_to City_30_32_33,
s_to City_32_34_33,
w_to City_32_31_33,
e_to City_32_33_35,
;

City_Class City_32_31_33 "32nd Ave between 31st St and 33rd St"
with
number 259,
w_to City_32_31,
e_to City_32_33,
;

City_Class City_30_32_33 "33rd St between 30th Ave and 32nd Ave"
with
number 241,
n_to City_30_33,
s_to City_32_33,
d_to Subway_Orange_30_32_33,
;

Storm_Class Storm_30_32_33 "Storm Drain below 33rd St between 30th Ave and 32nd Ave"
with
number 741,
u_to Subway_Orange_30_32_33,
w_to Storm_30_32_31,
e_to Storm_30_32_35,
;

City_Class City_32_34_33 "33rd St between 32nd Ave and 34th Ave"
with
number 279,
n_to City_32_33,
;

City_Class City_32_35 "32nd Ave and 35th St"
with
number 262,
n_to City_30_32_35,
s_to City_32_34_35,
w_to City_32_33_35,
e_to City_32_35_37,
;

City_Class City_32_33_35 "32nd Ave between 33rd St and 35th St"
with
number 261,
w_to City_32_33,
e_to City_32_35,
d_to Subway_Orange_32_33_35,
;

City_Class City_30_32_35 "35th St between 30th Ave and 32nd Ave"
with
number 243,
n_to City_30_35,
s_to City_32_35,
d_to Subway_Blue_30_32_35,
;

Storm_Class Storm_30_32_35 "Storm Drain below 35th St between 30th Ave and 32nd Ave"
with
number 743,
u_to Subway_Blue_30_32_35,
w_to Storm_30_32_33,
e_to Storm_30_32_37,
;

City_Class City_32_34_35 "35th St between 32nd Ave and 34th Ave"
with
number 281,
n_to City_32_35,
d_to Subway_Orange_32_34_35,
;

City_Class City_32_37 "32nd Ave and 37th St"
with
number 264,
n_to City_30_32_37,
s_to City_32_34_37,
w_to City_32_35_37,
e_to City_32_37_39,
;

City_Class City_32_35_37 "32nd Ave between 35th St and 37th St"
with
number 263,
w_to City_32_35,
e_to City_32_37,
d_to Subway_Blue_32_35_37,
;

City_Class City_30_32_37 "37th St between 30th Ave and 32nd Ave"
with
number 245,
n_to City_30_37,
s_to City_32_37,
d_to Storm_30_32_37,
;

Storm_Class Storm_30_32_37 "Storm Drain below 37th St between 30th Ave and 32nd Ave"
with
number 745,
u_to City_30_32_37,
w_to Storm_30_32_35,
n_to Storm_Junction_30_37,
;

City_Class City_32_37_39 "32nd Ave between 37th St and 39th St"
with
number 265,
w_to City_32_37,
d_to Storm_32_37_39,
;

Storm_Class Storm_32_37_39 "Storm Drain below 32nd Ave between 37th St and 39th St"
with
number 765,
u_to City_32_37_39,

n_to Storm_30_37_39,
s_to Storm_Junction_34_37,
;

City_Class City_32_34_37 "37th St between 32nd Ave and 34th Ave"
with
number 283,
n_to City_32_37,
s_to City_34_37,
;
